### ISSUE TITLE
Wrap GLFW events in Windowing.Desktop with try catch

### ISSUE THREAD

**Issue by PJB3005** [opentk/opentk#1003]
### Description

Right now the GLFW bind just calls into user code from the GLFW event handlers. The problem is that if you throw an exception in that user code it will unwind into GLFW. This can cause internal CLR errors and is just a terrible idea.

It would be best if exceptions would be caught and rethrown at the end of `ProcessEvents()`.

**Comment by NogginBops** [comment]
It seems like this is actually handled by the runtime?
Here is a stack trace of a project where I tried throwing an exception inside one of the callbacks (`<project path>` is the path to the project which I have removed from the stacktrace).
```
Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at AerialRace.Window.OnTextInput(TextInputEventArgs e) in <project path>\Window.cs:line 1277
   at OpenTK.Windowing.Desktop.NativeWindow.<.ctor>b__125_5(Window* w, UInt32 codepoint)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwPollEvents()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessEvents()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at AerialRace.Program.Main(String[] args)
```

Not sure how robust this is on other platforms other than Windows 10, but it might mean we don't need to worry about this.

**Comment by PJB3005** [comment]
Yes that's only safe on Windows because of SEH. On other platforms the behavior is completely undefined and will probably just result in a segfault/abort in the best case.
