### ISSUE TITLE
Requesting an OpenGL context of a version lower than 3.2 throws exception.

### ISSUE THREAD

**Issue by PJB3005** [opentk/opentk#1040]
### Description

Seems like we shouldn't pass the API profile to GLFW if the version is < 3.2, because it doesn't like it:

```
Unhandled exception. OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWException: Context profiles are only defined for OpenGL version 3.2 and above
   at OpenToolkit.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__5_0(ErrorCode errorCode, String description)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenToolkit.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenToolkit.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at opentk_test.Program.Main(String[] args) in /home/pj/Projects/scratch/opentk_test/Program.cs:line 22
``` 

### Repro steps

```cs
            var settings = NativeWindowSettings.Default;

            //settings.Profile = ContextProfile.Compatability;
            settings.APIVersion = new Version(3, 0);

            window = new GameWindow(GameWindowSettings.Default, settings);
```

### Related information 

* Operating system: Linux
* What version of OpenTK: 4.0.0-pre5
* What runtime: .NET Core 3.1.103
* Workarounds: Request 3.2

**Comment by SuperDIMMaX** [comment]
This not... bug... new GLFW can`t create OpenGL context < 3.2.
OpenTK 4.0 use GLFW
`[DllImport(LibraryName)]`
https://github.com/opentk/opentk/blob/ed3567def0b5b67cb0e28d93dedd7e421d4422b6/src/OpenToolkit.Windowing.GraphicsLibraryFramework/GLFWNative.cs#L228
You need recompile GLFW with context 2.1 (example), or use old version GLFW and add specific changes to OpenTK -_-
problem not in OpenTK -_- .... but i not 100% shure :/

**Comment by NogginBops** [comment]
Just tested this with a recent build of `master` and I can successfully create a 2.1 context by setting `APIVersion = new Version(2, 1)` and `Profile = ContextProfile.Any`.
