### ISSUE TITLE
I can't get it to work on Linux - Ubuntu 20.04

### ISSUE THREAD

**Issue by migueltk** [opentk/opentk#1058]
### Description

I have created a simple "rotating cube" project using OpenTK 4.0.0-pre9.1, and it runs on Windows but when I try to run it on Linux - Ubuntu 20.04, I get the following error message.

"./Test1Otk4
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libglfw.so.3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibglfw.so.3: cannot open shared object file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenToolkit.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenToolkit.Windowing.Desktop.NativeWindowSettings..ctor()
"
Files in "publish" folder;
"
glfw3-x64.dll		     
OpenToolkit.Windowing.Common.dll
glfw3-x86.dll		     
OpenToolkit.Windowing.Desktop.dll
libglfw.so.3.3		     
OpenToolkit.Windowing.GraphicsLibraryFramework.dll	     
runtimes
OpenToolkit.Core.dll	     
Test1Otk4
OpenToolkit.Graphics.dll     
Test1Otk4.deps.json
OpenToolkit.Input.dll	     
Test1Otk4.dll
OpenToolkit.Mathematics.dll  
Test1Otk4.pdb
OpenToolkit.OpenAL.dll	     
Test1Otk4.runtimeconfig.json
"
Here is the file with the sources of the project to Visual Studio;
https://drive.google.com/file/d/1IJ5oXgxSzCCBidLRc6NkiVtyboDAud7O/view?usp=sharing

Thank you all for the work done,
Cheers

### Related information 

* Operating system
Ubuntu 20.04
* What version of OpenTK (Installer, NuGet, Source Code)
OpenToolkit 4.0.0-pre9.1
* What runtime (.NET Framework, CoreCLR, Mono)
.Net core SDK 3.1.201

**Comment by jvbsl** [comment]
You can add a soft link from libglfw.so.3 to libglfw.so.3.3

**Comment by migueltk** [comment]
> You can add a soft link from libglfw.so.3 to libglfw.so.3.3

Yes, this works, thanks for the help ... :100: 
I hope it will be taken into account in future revisions so that the user does not have to manually add the link.

**Comment by jvbsl** [comment]
No worries, I am a full time linux user as well, and have already noticed that problem and want it fixed as well^^. Btw. if you would have installed the glfw libraries from the package manager it would probably have worked(does on Arch, as it creates a soft link like that)

**Comment by HugoPeters1024** [comment]
I am running into this exact issue as well, I already have glfw by compiling it myself but I'm not linux savvy enough to understand the work around you guys proposed. Could explain it in a bit more detail where I have to make the soft link?
