### ISSUE TITLE
GameWindow can not be created in 4.0.0-pre9.2 on Ubuntu

### ISSUE THREAD

**Issue by ables3000** [opentk/opentk#1104]
### Description

When upgrade from 4.0.0-pre9.1 to 4.0.0-pre9.2, an exception occurred in `new GameWindow(GameWindowSettings.Default, NativeWindowSettings.Default)`

### Repro steps

```csharp
using OpenToolkit.Windowing.Desktop;

public static void Main()
{
	var w= new GameWindow(GameWindowSettings.Default, NativeWindowSettings.Default);
	w.Run();
}
```

### Expected behavior

Display a window

### Actual behavior

Get exception

Exception has occurred: CLR/OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWException
An unhandled exception of type 'OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWException' occurred in OpenToolkit.Windowing.Desktop.dll: 'Invalid input mode 208900'
   at OpenToolkit.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__5_0(ErrorCode errorCode, String description)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWNative.glfwSetInputMode(Window* window, LockKeyModAttribute mode, Int32 value)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFW.SetInputMode(Window* window, LockKeyModAttribute mode, Boolean value)
   at OpenToolkit.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenToolkit.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)

### Related information 

* Ubuntu 18.04.4 LTS
* NuGet OpenTK 4.0.0-pre9.2
* .NET Core 3.1

**Comment by jvbsl** [comment]
Could you post the result of `apt-show-versions glfw3`?
My guess would be that the GLFW_LOCK_KEY_MODS which was introduced doesn't work for you, as it was only introduced with glfw3.3

**Comment by ables3000** [comment]
`libglfw3:amd64/bionic 3.2.1-1 uptodate`
`libglfw3:i386 not installed`

I will try to upgrade it to glfw3.3

**Comment by ables3000** [comment]
it works well after upgrade
