### ISSUE TITLE
Invalid casting

### ISSUE THREAD

**Issue by albfan** [opentk/opentk#1116]
### Description

Invalid casting running under flatpak in X11

```
00:00:00.932 |N| Application : Unhandled exception caught: System.InvalidCastException: Unable to cast object of type 'OpenTK.Platform.X11.X11WindowInfo' to type 'OpenTK.Platform.Linux.LinuxWindowInfo'.
   at OpenTK.Platform.Linux.LinuxFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GLWidget.Initialize()
   at OpenTK.GLWidget.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

### Expected behavior

Same code on host works, but not sure how to collect dotnet info and check what is different

### Actual behavior

Something is different in flatpak https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet, but not sure what.

### Related information 

https://github.com/flathub/flathub/pull/1778

* linux, flatpak
* Native backend (I guess)
* OpenTK (not sure)
* .NET 3.1

**Comment by Thog** [comment]
Ryujinx uses a custom version of OpenTK, I don't think this is the right repo for that.

**Comment by albfan** [comment]
Then probably get the opentk for offline build is the problem!

https://github.com/flathub/flathub/pull/1778/files#diff-970677ec35153c1e10e4f7a817f9ab69R224

that is grab from flatpak-dotnet-generator.py

**Comment by albfan** [comment]
Not sure how Ryujinx uses a custom OpenTk, flatpak build is using standard opentk at this moment

**Comment by jvbsl** [comment]
Did you find a solution or something new?
Otherwise you could try setting the platform backend to PreferNative before the Toolkit.Init method gets called.

**Comment by albfan** [comment]
@jvbsl tried all the options but error remains

**Comment by jvbsl** [comment]
did you set the options at the earliest time possible?
