### ISSUE TITLE
Unhandled Exception "Cannot marshal 'parameter #12' - Kubuntu 20.04

### ISSUE THREAD

**Issue by Starman0620** [opentk/opentk#1124]
### Description

Any time I try to write and run an OpenTK program I get an exception thrown at me no matter what specific code I'm trying to run.

### Repro steps

Attempt to run any OpenTK program under Kubuntu 20.04 with .NET Core 3.1, I am currently trying to run [this](https://github.com/opentk/opentk-examples/tree/master/src/BasicTriangle) example
### Expected behavior

Not much to be said about expected behaviour, I expect a Window to appear with a triangle

### Actual behavior

This exception
```
Unhandled exception. System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #12': Pointers cannot reference marshaled structures.  Use ByRef instead.
   at OpenTK.Platform.X11.Functions.XCreateWindow(IntPtr display, IntPtr parent, Int32 x, Int32 y, Int32 width, Int32 height, Int32 border_width, Int32 depth, Int32 xclass, IntPtr visual, IntPtr valuemask, XSetWindowAttributes* attributes)
   at OpenTK.Platform.X11.X11GLNative..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device)
   at OpenTK.Platform.X11.X11Factory.CreateNativeWindow(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device)
   at OpenTK.NativeWindow..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device)
   at OpenTK.NativeWindow..ctor(Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext, Boolean isSingleThreaded)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device)
   at OpenTK.GameWindow..ctor()
   at BasicTriangle.Program..ctor() in /home/cam/Desktop/TKGame/Program.cs:line 30
   at BasicTriangle.Program.Main() in /home/cam/Desktop/TKGame/Program.cs:line 128
```

### Related information 

* Kubuntu 20.04
* Not sure about the backend
* Nuget through the ``dotnet add`` command
* .NET Core 3.1 (I suspect this could be the issue but I'm not entirely sure)

**Comment by jvbsl** [comment]
OpenTK 3.2 does not work with dotnet core(well some things perhaps do) but it was never made to work with Core. 4.x Is made for .net core only(and .Net 5 should work as well). You could try using the prerelease packages, while the API changed a little, it should be usable.
Otherwise you need to use .Net Framework/Mono respectively

**Comment by Starman0620** [comment]
That did the trick, thank you!
