### ISSUE TITLE
Windows: System.DllNotFoundException: openal32.dll 

### ISSUE THREAD

**Issue by Davilink** [opentk/opentk#1169]
I create a project example to play with around with sound capture using OpenTK.OpenAL and it work on linux, but the same code crash on windows.
### Description
```pwsh
Unhandled exception. System.DllNotFoundException: Could not load the dll 'openal32.dll' (this load is intercepted, specified in DllImport as 'AL').
   at OpenTK.Audio.OpenAL.ALLoader.ImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Audio.OpenAL.ALC.CaptureOpenDevice(String devicename, Int32 frequency, ALFormat format, Int32 buffersize)
   at MyRecorder.Recorder.DoRecording() in C:\Users\dpelletier\Desktop\test2\MyRecorder\Recorder.cs:line 43
   at MyRecorder.Recorder.Run() in C:\Users\dpelletier\Desktop\test2\MyRecorder\Recorder.cs:line 28
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

* Operating system Windows 10
* SDL or Native backend ???
* What version of OpenTK (Installer, NuGet, Source Code) Nuget 4.0.3
* What runtime (.NET Framework, CoreCLR, Mono) .netcore 3.1

**Comment by Davilink** [comment]
@NogginBops Thank. Is there a reason why the dll is not bundled with the nuget package ?

**Comment by subchannel13** [comment]
Historically Windows had that dll by default. It's OS's library rather than OpenTK's

**Comment by Davilink** [comment]
Could it be possible to do it ?

**Comment by NogginBops** [comment]
It is possible to bundle a version of openal with opentk yes, but the problem is what openal version.
There are multiple versions of openal, the 'recommended' version is the one the Creative makes, but openal soft is a good alternative for bundling with an application. Other audio card vendors also have their own openal implementations.
So it's not clear like opengl where and what library to talk to.
