### ISSUE TITLE
GLFW dll requires VC++ redist to be installed

### ISSUE THREAD

**Issue by CaiB** [opentk/opentk#1228]
### Description

After updating my application to OpenTK 4 from 3, I receive a DllNotFoundException at startup:
`System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)`

### Repro steps
1. Download [latest version of my application](https://github.com/CaiB/ColorChord.NET/releases/tag/auto-v0.6.0.113)
2. Execute
3. Crashes at startup while trying to initialize `DisplayOpenGL` (my `GameWindow`-deriving class)

I can even reproduce this using the ["Creating a Window" Tutorial code](https://github.com/opentk/LearnOpenTK/tree/master/Chapter1/1-CreatingAWindow):
1. Download code from linked project
2. Open in VS2019
3. Switch target framework to .NET 5.0
4. Change output type to Console Application
5. Build in release mode
6. Run on dev machine, works fine
7. Copy to media center PC, crashes with same exception.

### Expected behavior
I would like it to not crash if possible :(

### Actual behavior
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'OpenTK.Windowing.Desktop.NativeWindowSettings' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.NativeWindowSettings..ctor()
   at OpenTK.Windowing.Desktop.NativeWindowSettings..cctor()
   --- End of inner exception stack trace ---
   at ColorChord.NET.Outputs.DisplayOpenGL.SetupNativeWindow() in C:\projects\colorchord-net\ColorChord.NET\Outputs\DisplayOpenGL.cs:line 46
   at ColorChord.NET.Outputs.DisplayOpenGL..ctor(String name) in C:\projects\colorchord-net\ColorChord.NET\Outputs\DisplayOpenGL.cs:line 38
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ColorChord.NET.ColorChord.CreateObject[InterfaceType](String fullName, JToken configEntry, Boolean complexConfig) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 126
   at ColorChord.NET.ColorChord.ReadConfig() in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 107
   at ColorChord.NET.ColorChord.Main(String[] args) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 32
```

From the tutorial project:
```
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.NativeWindowSettings..ctor()
   at LearnOpenTK.Program.Main() in [SNIP]\LearnOpenTK-master\Chapter1\1-CreatingAWindow\Program.cs:line 11
```

### Related information 
I was able to run the OpenTK 3-based version on this same computer without issue.  
I found #1108 but this was apparently resolved and seemed slightly different.
I can run this exact same build on my dev computer without issue as well, also running .NET 5.0.

* Windows 10 Pro x64 2004 (19041.685)
* Intel HD Graphics 4000 (Driver ver 10.18.10.4252, date 2015-07-09) / AMD Radeon HD 7800M Series (Driver ver 26.20.12028.2, date 2019-08-15)
* SDL or Native backend?: Not sure what this means
* OpenTK 4.4 (latest) from NuGet
* .NET Runtime 5.0

**Comment by pvlpxl** [comment]
Had the same issue, but it fixed itself after I installed Mono.

**Comment by NogginBops** [comment]
Is this still an issue?
I tried the repro but it didn't crash for me.

This is likely something related to nuget and or how the system searches for dlls.
Not sure where to start debugging this issue.

**Comment by Itee** [comment]
I had the same too.
I just cloning the repository, start the build.cmd and create a fresh console app from scratch.

The exception is throw from GLFWNative.cs at line 69 but the real error come from line 11.
`private const string LibraryName = "glfw3.dll";` // hard code... 

The debug/release output contain glfw3**-x64**.dll and glfw3**-x86**.dll.

I let you find the prettiest solution to fix this ;)

As quick fix you can just rename the appropriate platform dll to glw3.dll and it will work.

Hope this help,
Best regards.

**Comment by NogginBops** [comment]
@Itee Line 11 is actually not the issue happening here.
`"glfw3.dll"` is just a name used as a tag for the `NativeLibrary` import solver that is registered [here](https://github.com/opentk/opentk/blob/master/src/OpenTK.Windowing.GraphicsLibraryFramework/GLFWNative.cs#L20-L28).

We actually do try quite a few names when looking for the glfw dll.
On most machines it seems to work fine. My guess is that there is some rare windows configuration that doesn't allow the correct dll to be found.
Either as some edge case in the import resolver or some other circumstance.

I'm curious what tools you are using to build and run the project.
Are you using a comand line tool or are you using something like Visual Studio or Rider?

**Comment by CaiB** [comment]
I'm still encountering the issue.

I've tried building both with Visual Studio 2019 (16.9.3), and my project's auto-built releases are built using MSBuild 16.9.0.16703 currently. Both versions exhibit the same behaviour.

It only happens on one of my computers (a non-dev machine), and several other people are using my project without issue as well. There's very little on this computer. It has just a few basic programs installed, and is just used to play music and videos off my server on the TV. No dev tools, no crazy configuration.

I see that in a subfolder called `runtimes/win-x64/native` there's a `glfw3.dll`. I tried copying this out to the root folder beside the EXE, and renaming to just `glfw.dll`, and the same with the `win-x86` version. None of these attempts helped at all.

I'm now using:
- OpenTK 4.6.3 from NuGet
- .NET Runtime 5
- Windows 10 Pro 20H2 19042.928 x64
- Intel HD Graphics 4000 (Driver ver 10.18.10.4252, date 2015-07-09) / AMD Radeon HD 7800M Series (Driver ver 27.20.1034.6, date 2020-08-20)

Please let me know if there's any other information that might be helpful!

The exception I get:
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'OpenTK.Windowing.Desktop.NativeWindowSettings' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.NativeWindowSettings..ctor()
   at OpenTK.Windowing.Desktop.NativeWindowSettings..cctor()
   --- End of inner exception stack trace ---
   at ColorChord.NET.Outputs.DisplayOpenGL.SetupNativeWindow() in C:\projects\colorchord-net\ColorChord.NET\Outputs\DisplayOpenGL.cs:line 46
   at ColorChord.NET.Outputs.DisplayOpenGL..ctor(String name) in C:\projects\colorchord-net\ColorChord.NET\Outputs\DisplayOpenGL.cs:line 38
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ColorChord.NET.ColorChord.CreateObject[InterfaceType](String fullName, JToken configEntry, Boolean complexConfig) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 127
   at ColorChord.NET.ColorChord.ReadConfig() in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 108
   at ColorChord.NET.ColorChord.Main(String[] args) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 33
```

**Comment by notgiven688** [comment]
> Had the same issue, but it fixed itself after I installed Mono.

Same here. Fresh virtual machine with .NET SDK 5.0 fails. After installing mono it works.

**Comment by CaiB** [comment]
I was under the impression that just keeping a normal reference doesn't prevent the delegate from being moved in memory, preventing some optimizations?

**Comment by CaiB** [comment]
Oh, interesting. Thanks for the explanation!

I'll make sure to add that later, but the DLL issue still remains. Is there any more info I can provide to help track down that issue?
