### ISSUE TITLE
[3.x] InvalidOperationException: [Input] Invalid GamePad configuration value

### ISSUE THREAD

**Issue by YoshiRulz** [opentk/opentk#1559]
### Description

Calling `GamePad.GetState` on app startup while a certain model of gamepad is plugged in causes it to crash.

### Repro steps

Clone [repro project](https://github.com/YoshiRulz/opentk-1559-repro), `dotnet build && mono bin/Debug/OTKRepro.exe`.
(If doing this IRL, remember to hold a button on the gamepad when starting Mono, otherwise it won't be detected.)

### Expected behavior

Doesn't throw, and `GamePad.GetState(0).IsConnected is true`

### Actual behavior

```
System.InvalidOperationException: [Input] Invalid GamePad configuration value
  at OpenTK.Input.GamePadConfiguration.ParseSource (System.String item) [0x00056] in <9314f5d039f340638e3a78d50aa1a6d0>:0 
  at OpenTK.Input.GamePadConfiguration.ParseConfiguration (System.String configuration) [0x00062] in <9314f5d039f340638e3a78d50aa1a6d0>:0 
  at OpenTK.Input.GamePadConfiguration..ctor (System.String configuration) [0x00011] in <9314f5d039f340638e3a78d50aa1a6d0>:0 
  at OpenTK.Platform.MappedGamePadDriver.GetConfiguration (System.Guid guid) [0x0001b] in <9314f5d039f340638e3a78d50aa1a6d0>:0 
  at OpenTK.Platform.MappedGamePadDriver.GetState (System.Int32 index) [0x00038] in <9314f5d039f340638e3a78d50aa1a6d0>:0 
  at OpenTK.Input.GamePad.GetState (System.Int32 index) [0x00000] in <9314f5d039f340638e3a78d50aa1a6d0>:0 
  at Program.<<Main>$>g__InitGamepads|0_0 () [0x00005] in <606ba0ca36e847498b15c85bd8e5ded1>:0 
  at Program.<Main>$ (System.String[] args) [0x00008] in <606ba0ca36e847498b15c85bd8e5ded1>:0
```

### Related information 

Crashes on Debian 11, Mono 6.12.0.182. Hardware is an iNext 'GAME CONTROLLER' 0079-0011 (SNES clone).

Repro project targets .NET Framework 4.8 and uses OpenTK 3.3.3 from NuGet. Only the Input types are used.

**Comment by shaoyidi** [comment]
I'm using Windows 10 with Opentk version 3.3.3 and Opentk.GLControl version 3.3.3 in a .NET Framework 4.7.2 WPF project. Debugging and releasing in Visual Studio both work fine, but after packaging and installing, the program crashes with an error when run on a debugging computer.

Application: MyApplication.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
   at OpenTK.Graphics.OpenGL.GL..cctor()
   at OpenTK.Graphics.OpenGL.GL.get_DrawingBuffer()
   at OpenTK.GLControl.CreateGraphicsContext(Boolean)
   at OpenTK.GLControl.OnHandleCreated(System.EventArgs)
   at System.Windows.Forms.Control.WmCreate(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

**Comment by NogginBops** [comment]
@shaoyidi this seems like a separate issue to me. Could you open a separate issue for this?

**Comment by NogginBops** [comment]
Calling `Guid Joystick.GetGuid(int index)` should give you the guid of the device you are calling `GetState(int index)` for.

**Comment by YoshiRulz** [comment]
It is `03000000-7900-0000-1100-000010010000`.
