### ISSUE TITLE
Reflection causes runtime exceptions when Publishing with Trimmed Assemblies

### ISSUE THREAD

**Issue by xormak** [opentk/opentk#1595]
## Description

OpenTK produces runtime exceptions when published using the "Trim unused Libraries" option and/or using NativeAoT.
This seems to stem from the use of `System.Reflection` in `OpenTK.Windowing.Desktop/NativeWindow.cs`.
An example of that would be the use of `Assembly.Load()` on line 941.

### 1. Step 
Create an `OpenTK 4.7.7` project and follow the Learn OpenTK Tutorial until the first GL commands are used. (Hello triangle)

The deciding part seems to be the use of a class derived from `NativeWindow`.

### 2. Step 
Create a publishing profile 
- Deployment: Self-Contained
- Target Runtime: win-x64 (Other runtimes most likely yield the same result)
- Options:
  - Trim unused Assemblies

## 3. Step
Now publish the project and run it. It should produce an error similar to this:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenTK.Windowing.Desktop.NativeWindow.<InitializeGlBindings>g__LoadBindings|139_0(String, <>c__DisplayClass139_0&)   at OpenTK.Windowing.Desktop.NativeWindow.InitializeGlBindings()
   at OpenTK.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings)
   at OpenTK.Windowing.Desktop.GameWindow..ctor(GameWindowSettings, NativeWindowSettings)
   at OpenTKBug.Program.Main() in ...\Program.cs:line 22

[process exited with code 3221225477 (0xc0000005)]
```
(Attached Solution)
[OpenTKBug.zip](https://github.com/opentk/opentk/files/11670746/OpenTKBug.zip)

## Expected behavior

I expect to be able to publish my application with trimmed assemblies to save on disk space.
This would also allow the use of NativeAoT.

## Actual behavior

The project gets published with trim warnings and produces the Runtime Exception shown above when executed.

```
OpenTK.Windowing.Desktop.dll: [IL2104] Assembly 'OpenTK.Windowing.Desktop' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries
```

## Related information 

* Windows 11 Pro
* Native Backend
* Nuget 4.7.7
* .Net 7.0

**Comment by NogginBops** [comment]
Seems like we need to add some (`[DynamicDependency]`)[https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicdependencyattribute?view=net-7.0] attributes to the NativeWindow code.
I'm guessing that would fix the issue.

**Comment by NogginBops** [comment]
This solution was confirmed to work in discord. Unfortunately OpenTK targets .net core 3.1 which doesn't have the `[DynamicDependency]` attribute so we can't properly fix the issue in C# code (without trying to add out compile targets which is a more complicated process than it should be, but I might consider it).

I will make a PR where I add an exception message that might be helpful.

**Comment by NogginBops** [comment]
This will also need to be considered for OpenTK 5.
