### ISSUE TITLE
System.TypeInitializationException in OpenTK.Input.Joystick

### ISSUE THREAD

**Issue by anaym** [opentk/opentk#384]
I use XBOX 360 controller. And this code:
```
var caps = GamePad.GetCapabilities(i);
if (caps.HasAButton)
      ; // do something

       // Print all capabilities for this GamePad
        f.WriteLine(caps.ToString());
```
throw TypeInitializationException

**Comment by wcdeich4** [comment]
Hmm.  Strangely I just had exactly the same error.  Except, I got it when I tried an experiment by adding a console application directly to the OpenTK source code & changed the target framework to .NET 4.0. 

System.TypeInitializationException was unhandled
  HResult=-2146233036
  Message=The type initializer for 'OpenTK.DisplayDevice' threw an exception.
  Source=OpenTK
  TypeName=OpenTK.DisplayDevice
  StackTrace:
       at OpenTK.DisplayDevice.get_Default()
       at OpenTK.GameWindow..ctor() in c:\Users\Will\Matrix\CODE\WinOpenGL\OpenTK_Test\Source\OpenTK\GameWindow.cs:line 115
       at Demo.Program.Main(String[] args) in c:\Users\Will\Matrix\CODE\WinOpenGL\OpenTK_Test\Demo\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.TypeInitializationException
       HResult=-2146233036
       Message=The type initializer for 'OpenTK.Platform.Factory' threw an exception.
       Source=OpenTK
       TypeName=OpenTK.Platform.Factory
       StackTrace:
            at OpenTK.Platform.Factory.get_Default()
            at OpenTK.DisplayDevice..cctor() in c:\Users\Will\Matrix\CODE\WinOpenGL\OpenTK_Test\Source\OpenTK\DisplayDevice.cs:line 68
       InnerException: System.MethodAccessException
            HResult=-2146233072
            Message=Attempt by security transparent method 'OpenTK.Platform.Windows.WinFactory.LoadOpenGL()' to call native code through method 'OpenTK.Platform.Windows.Functions.LoadLibrary(System.String)' failed.  Methods must be security critical or security safe-critical to call native code.
            Source=OpenTK
            StackTrace:
                 at OpenTK.Platform.Windows.WinFactory.LoadOpenGL() in c:\Users\Will\Matrix\CODE\WinOpenGL\OpenTK_Test\Source\OpenTK\Platform\Windows\WinFactory.cs:line 78
                 at OpenTK.Platform.Windows.WinFactory..ctor() in c:\Users\Will\Matrix\CODE\WinOpenGL\OpenTK_Test\Source\OpenTK\Platform\Windows\WinFactory.cs:line 62
                 at OpenTK.Platform.Factory..ctor() in c:\Users\Will\Matrix\CODE\WinOpenGL\OpenTK_Test\Source\OpenTK\Platform\Factory.cs:line 63
                 at OpenTK.Toolkit.Init(ToolkitOptions options) in c:\Users\Will\Matrix\CODE\WinOpenGL\OpenTK_Test\Source\OpenTK\Toolkit.cs:line 141
                 at OpenTK.Toolkit.Init() in c:\Users\Will\Matrix\CODE\WinOpenGL\OpenTK_Test\Source\OpenTK\Toolkit.cs:line 91
                 at OpenTK.Platform.Factory..cctor() in c:\Users\Will\Matrix\CODE\WinOpenGL\OpenTK_Test\Source\OpenTK\Platform\Factory.cs:line 51
            InnerException:

**Comment by varon** [comment]
This might relate to #358.

Could you try the workaround listed there?
>A temporary workaround is to use the NuGet package version 1.1.1589.5942 instead of the latest 1.1.2225, in which this issue isn't present.

A fix for this issue has already been pushed, so we're currently working on updating the NuGet package. Estimated time for that should be the end of this week.

**Comment by varon** [comment]
@anaym - Could you try the latest pre-release NuGet packages, and see if they fix this issue for you?

>The pre-release packages can be downloaded here:
https://www.nuget.org/packages/OpenTK.Next/1.2.2336.6514-pre
https://www.nuget.org/packages/OpenTK.Next.GLControl/1.2.2336.6514-pre

(Note, that if you wish to install from your IDE or the command line, you might need to enable "show pre-releases" for them to appear)

**Comment by anaym** [comment]
Yes, thank you, it works

**Comment by varon** [comment]
Thanks for reporting back, @anaym! Glad to hear it's solved.
