### ISSUE TITLE
OpenTK can no longer be used as part of a obfuscated project using ConfuserEX

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#659]
ConfuserEX needs to read/write all dependencies. Using the latest build of opentk, while trying to write opentk.dll it fails with following exception. Any ideas what that could be?

```
Exception: dnlib.DotNet.Writer.ModuleWriterException: Error calculating max stack value. If the method's obfuscated, set CilBody.KeepOldMaxStack or MetaDataOptions.Flags (KeepOldMaxStack, global option) to ignore this error. 
Otherwise fix your generated CIL code so it conforms to the ECMA standard. 
at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args) in E:\Source\Public\Confuser2\dnlib\src\DotNet\ILogger.cs:line 456
   at dnlib.DotNet.Writer.MetaData.dnlib.DotNet.Writer.IWriterError.Error(String message) in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MetaData.cs:line 2575
   at dnlib.DotNet.Writer.MethodBodyWriterBase.GetMaxStack() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MethodBodyWriterBase.cs:line 64
   at dnlib.DotNet.Writer.MethodBodyWriter.Write() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MethodBodyWriter.cs:line 95
   at dnlib.DotNet.Writer.MetaData.WriteMethodBodies() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MetaData.cs:line 1552
   at dnlib.DotNet.Writer.MetaData.Create() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\MetaData.cs:line 1206
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\ModuleWriter.cs:line 171
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest) in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\ModuleWriterBase.cs:line 503
   at Confuser.Core.ConfuserEngine.WriteModule(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 393
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContextcontext) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 135
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 244
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 175
Failed at 9:59 PM, 0:28 elapsed.
```

**Comment by Nihlus** [comment]
It's quite likely this is a reaction to the rewrite step of the build process, wherein _calli instructions are injected. Did this happen with previous versions of OpenTK?

**Comment by tyronx** [comment]
Not with 1.1.4, did not test yet with 2.0.0

**Comment by Frassle** [comment]
We could try running [PEVerify](https://docs.microsoft.com/en-us/dotnet/framework/tools/peverify-exe-peverify-tool), that might pick up the metadata issues and tell us more precisely where it's wrong.

**Comment by UnknownShadow200** [comment]
I modified dnlib to output name of methods it was writing, it fails on: 
`
System.Void OpenTK.Graphics.OpenGL.GL/Intel::GetPerfCounterInfo(System.Int32,System.Int32,System.Int32,System.String&,System.Int32,System.String&,System.Int32[],System.Int32[],System.Int32[],System.Int32[],System.Int64[])`
(Note: This is the first overload of GetPerfCounterInfo it attempts to write)

ILSpy also fails to decompile the method:
```
 ---> System.OverflowException: Array dimensions exceeded supported range.
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackSlot.ModifyStack(StackSlot[] stack, Int32 popCount, Int32 pushCount, ByteCode pushDefinition)
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDefinition methodDef)
```

I'll keep investigating as to what causes the issue.

**Comment by Frassle** [comment]
Found it. These methods are using "out string" parameters but don't have CountAttributes on them. The code in rewrite that was supposed to detect this case had a silly bug. Will start a PR.

**Comment by Frassle** [comment]
And the underlying issue seems to be that these string parameters were marked out when they aren't actually out.
OpenGL XML:
```
        <command>
            <proto>void <name>glGetPerfQueryIdByNameINTEL</name></proto>
            <param><ptype>GLchar</ptype> *<name>queryName</name></param>
            <param><ptype>GLuint</ptype> *<name>queryId</name></param>
        </command>
```
OpenTK XML:
```
    <function name="GetPerfQueryIdByNameINTEL" category="INTEL_performance_query" extension="INTEL">
      <param name="queryName" type="GLchar *" flow="out" />
      <param name="queryId" type="GLuint *" flow="out" />
      <returns type="void" />
    </function>
```

Not sure how we detect and fix this? Don't make char* params out unless they have count attribute?

**Comment by Frassle** [comment]
Seems the best way of fixing this is to just use overrides.xml to fill in the data missing from the official spec files. However there's a bug in the generator when using overrides.xml to replace the count attribute. It doesn't update ComputeSize, only ElementCount. Fixing it to update both causes a load of functions to change because now they think they have a size of 0 instead of 1, because we abused overrides.xml to add array overloads of functions when Khronos changed they're count parameters from nothing to "1" by adding overrides with count set to "0".

All in all , a tonne of legacy crap means fixing this is surprisingly hard.
