### ISSUE TITLE
OpenTK throws OpenTK.Graphics.GraphicsContextException: Could not create GL context: BadValue (integer parameter out of range for operation) on Run

### ISSUE THREAD

**Issue by Chris3606** [opentk/opentk#686]
### Description

Both the Mono and .NET Core versions of OpenTK on Nuget are throwing an exception with the message "Unhandled Exception: OpenTK.Graphics.GraphicsContextException: Could not create GL context: BadValue (integer parameter out of range for operation)", when compiled and run on Linux Mint 18.2.  My computer is running the most recent NVIDIA (proprietary) driver and a GTX 660 SC graphics card.

My computer is also dual-booted to Windows 10: when compiled and run on the same computer but running Windows 10 everything works as expected.

### Repro steps

1. Open MonoDevelop, and create a new C# console application.
2. Add the OpenTK Nuget package.  Ensure the OpenTK package config file is being copied to the output directory on build.
3. Add the following code to the Program.cs file:
`
using OpenTK;
namespace MyApp
{
    class Game : GameWindow {}
    class Program
    {
        static void Main(string[] args)
        {
            using (Game game = new Game())
            {
                game.Run(30.0);
            }
        }
    }
}
`
4. Compile and run the program.

### Expected behavior

A basic window should be displayed.

### Actual behavior

An exception is thrown with the message: `Unhandled Exception: OpenTK.Graphics.GraphicsContextException: Could not create GL context: BadValue (integer parameter out of range for operation)
   at OpenTK.Platform.SDL2.Sdl2GraphicsContext..ctor(GraphicsMode mode, IWindowInfo win, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Platform.SDL2.Sdl2Factory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext)
   at OpenTK.GameWindow..ctor()
   at MyApp.Game..ctor()
   at MyApp.Program.Main(String[] args) in /home/chris/Development/CSharp/Core/MyApp/Program.cs:line 16
`

### Related information 

* OS: Linux Mint 18.2
* Native backend
* NuGet version of OpenTK
* Mono runtime (.NET Core as well)

**Comment by Nihlus** [comment]
Please try the latest version of OpenTK from the MyGet feed. The NuGet version is severely outdated.

**Comment by Chris3606** [comment]
Tried that and it worked fine.  Furthermore I went back and tried the version that failed last night (from NuGet) and it seemed to work as well.  Something on my system must have been borked -- oh well.  Closing.
