### ISSUE TITLE
AccessViolationException throws from OpenTK.dll if I use Shader from OpenTK.Graphics.OpenGL4 

### ISSUE THREAD

**Issue by sourceskyboxer** [opentk/opentk#749]
### Description
It happens from GL.CreateShader() and it throws since 1 hour - It happens - I thought OpenTK.dll was from MyGet ( OpenTK's Development )

Please provide a succinct description of your issue.
It is only AccessViolationException - I don't know how do I fix?

### Repro steps
Since Loading shader file or embedded shader string happens since running Shader content

Please provide the steps required to reproduce the problem

1. Step A
Extended files ( *.txt or *.shader ) or embedded string @" ... " run since GL.CreateShader and GL.ShaderSource

2. Step B
It throws like GameWindow exits unfortunately cause GL.CreateShader from OpenGL4

### Expected behavior
AccessViolationException 

Please provide a description of the behavior you expect.
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenTK.Graphics.OpenGL4.GL.CreateShader(ShaderType type) in D:\temp\e7dd768\src\OpenTK\Graphics\OpenGL4\GL4.cs:line 15049
   at Tutorial_04.net.sourceskyboxer.ShaderProgram..ctor() in C:\Users\SSB\source\repos\MyTestWinForm\Tutorial_04\net\sourceskyboxer\ShaderProgram.cs:line 13
   at Tutorial_04.Game..ctor() in C:\Users\SSB\source\repos\MyTestWinForm\Tutorial_04\Game.cs:line 18
   at Tutorial_04.Program.Main(String[] args) in C:\Users\SSB\source\repos\MyTestWinForm\Tutorial_04\Program.cs:line 7
```

* Operating system Windows 10 ( x86 / x64 )
* SDL - or Native backend X
* What version of OpenTK (Installer, NuGet, Source Code) Very latest OpenTK-Development from MyGet
* What runtime (.NET Framework, CoreCLR, Mono) Net Frameworks 4.5 / Mono 4.5 ( Mono-Installation\lib\mono\4.5 )
* Workarounds (if any) Can't try I have tried if I make without abstract - nothing and virtual method nothing etc.. nothing gets working. :(

**Comment by sourceskyboxer** [comment]
It fixed because somebody need declare variable than in override method onLoad() new class of instance ! It resolved thanks! But you're really stubborm to me. Why do you not say me before? But I don't know about AccessViolationException since I got initial time. I never get "AccessViolationException" since starting with C# - I thought instance like Actionscript 3 like this
`private classname myclass;`

in Load override method or constructor 
`myclass = new classname();`

It works fine. Now closed issue!
