### ISSUE TITLE
GameWindow CreateContext Crashes with Memory Corrupt Error

### ISSUE THREAD

**Issue by sleman** [opentk/opentk#888]
### Description

App crashes when I try to call GameWindow().

### Repro steps

Please provide the steps required to reproduce the problem

```
GameWindow window = new GameWindow(100, 100);
```

Happening with different graphics cards:

Intel(R) HD Graphics 520
Intel(R) HD Graphics 620
Intel(R) HD Graphics 630

### Expected behavior

App does not crash

### Actual behavior

App crashes with this error:
```
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenTK.Platform.Windows.Wgl.CreateContext(IntPtr hDc)
   at OpenTK.Platform.Windows.WinGLContext.TemporaryContext..ctor(INativeWindow native)
   at OpenTK.Platform.Windows.WinGLContext..ctor(GraphicsMode format, WinWindowInfo window, IGraphicsContext sharedContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Platform.Windows.WinFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height)
   at Core.Classes.GreenScreenHelper.InitOpenGl() in C:\Users\Michael\Documents\app\Core\Classes\GreenScreenHelper.cs:line 385
   at classes.Logger.LogSystemInfo() in C:\Users\Michael\Documents\app\classes\Logger.cs:line 400
   at MainWindow..ctor() in C:\Users\Michael\Documents\app\MainWindow.xaml.cs:line 68
OpenTK
```
### Related information 

* Microsoft Windows NT 10.0.14393.0
* Using C# 
* What version of OpenTK: NuGet 3.0.1.0
* .NET Framework .NET 4.6.2
* Have not found any workarounds.

**Comment by Perksey** [comment]
My first guess is that you never call Toolkit.Init(). This should be done at the beginning of the program.

**Comment by jvbsl** [comment]
@Perksey pretty sure thats not the reason:
https://github.com/opentk/opentk/blob/3.0/src/OpenTK/Platform/Factory.cs#L46
A Factory is needed to create a Window and if you use the implemented GameWindow the Factory will automatically call the Toolkit.Init() function...

Don't know the actual Problem though. Would be interested in the chosen GraphicsMode as well as major and minor version(as I myself had some problems with them on Windows)...

**Comment by sleman** [comment]
I did not explicitly set a GraphicsMode or major/minor versions. Are there specific ones I should test?

**Comment by varon** [comment]
Give 4.6 a shot and see what you get.

**Comment by sleman** [comment]
The latest I see in [Nuget ](https://www.nuget.org/packages/OpenTK/) is 3.0.1 

Do you mean install from source?

**Comment by Perksey** [comment]
He means OpenGL 4.6 :P

**Comment by sleman** [comment]
Tried the following and it still crashed:

`                    window = new GameWindow(100, 100, GraphicsMode.Default, "", GameWindowFlags.Default, DisplayDevice.Default, 4, 6, GraphicsContextFlags.Default);`

**Comment by sleman** [comment]
So this exception crashes my app. Why isn't this caught by OpenTK?

**Comment by Perksey** [comment]
Because it happens when doing a critical call to initialize the GameWindow. Have a look at the debug log (not the console log) to see if anything is put there as I'm utterly clueless. One of the calls is returning an invalid pointer.

**Comment by varon** [comment]
Should be fixed by 4.x
