### ISSUE TITLE
Exception on Linux when creating GameWindow

### ISSUE THREAD

**Issue by cody82** [opentk/opentk#894]
I am trying to Run OpenTK on Ubuntu 18.10 with dotnet installed from snap using the OpenTK NuGet Package.
But I get this Exception when creating the GameWindow. What could be wrong?

Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #12': Pointers cannot reference marshaled structures.  Use ByRef instead.
   at OpenTK.Platform.X11.Functions.XCreateWindow(IntPtr display, IntPtr parent, Int32 x, Int32 y, Int32 width, Int32 height, Int32 border_width, Int32 depth, Int32 xclass, IntPtr visual, IntPtr valuemask, XSetWindowAttributes* attributes)
   at OpenTK.Platform.X11.X11GLNative..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device) in /home/jarl/Programming/opentk-3.0/src/OpenTK/Platform/X11/X11GLNative.cs:line 205
   at OpenTK.Platform.X11.X11Factory.CreateNativeWindow(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device) in /home/jarl/Programming/opentk-3.0/src/OpenTK/Platform/X11/X11Factory.cs:line 64
   at OpenTK.NativeWindow..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device) in /home/jarl/Programming/opentk-3.0/src/OpenTK/NativeWindow.cs:line 109
   at OpenTK.NativeWindow..ctor(Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device) in /home/jarl/Programming/opentk-3.0/src/OpenTK/NativeWindow.cs:line 74
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext, Boolean isSingleThreaded) in /home/jarl/Programming/opentk-3.0/src/OpenTK/GameWindow.cs:line 186
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title) in /home/jarl/Programming/opentk-3.0/src/OpenTK/GameWindow.cs:line 119
   at dotnet.Game..ctor(Int32 width, Int32 height, String title) in /home/cody/dotnet/Game.cs:line 12
   at dotnet.Program.Main(String[] args) in /home/cody/dotnet/Program.cs:line 11

**Comment by devvoid** [comment]
Can you show us the program you're trying to use?

Also, can you show us your .csproj? We've had a lot of issues with people accidentally using forks of OpenTK instead of the official project.

**Comment by Perksey** [comment]
This one looks like an official package as it has Nihlus' paths in the stack trace

**Comment by cody82** [comment]
Here is the project:
[dotnet2.zip](https://github.com/opentk/opentk/files/3069568/dotnet2.zip)

**Comment by devvoid** [comment]
OpenTK doesn't support dotnet core yet. Official support is on the way in 4.0, but it's still a while off.

**Comment by devvoid** [comment]
OpenTK doesn't support dotnet core yet. Official support is on the way in 4.0, but it's still a while off.

**Comment by cody82** [comment]
Ok, thank you.
