### ISSUE TITLE
GameWindow Throws MarshalDirectiveException

### ISSUE THREAD

**Issue by kawaemon** [opentk/opentk#896]
### Description

GameWindow throws System.Runtime.InteropServices.MarshalDirectiveException.

### Repro steps

1. Run this code.
```
using System;
using OpenTK;
using OpenTK.Graphics;

namespace OpenGL.Test {
    public class Test {
        [STAThread]
        public static void Main(string[] args) {
            using (GameWindow w = new GameWindow(1920,1080, GraphicsMode.Default, "HelloWorld")) {
                w.Run(60.0);
            }
        }
    }
}
```

### Expected behavior

GameWindow doesn't throw any exception.

### Actual behavior

GameWindow throws this exception.
```
Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #12': Pointers cannot reference marshaled structures.  Use ByRef instead.
   at OpenTK.Platform.X11.Functions.XCreateWindow(IntPtr display, IntPtr parent, Int32 x, Int32 y, Int32 width, Int32 height, Int32 border_width, Int32 depth, Int32 xclass, IntPtr visual, IntPtr valuemask, XSetWindowAttributes* attributes)
   at OpenTK.Platform.X11.X11GLNative..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device) in /home/jarl/Programming/opentk-3.0/src/OpenTK/Platform/X11/X11GLNative.cs:line 205
   at OpenTK.Platform.X11.X11Factory.CreateNativeWindow(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device) in /home/jarl/Programming/opentk-3.0/src/OpenTK/Platform/X11/X11Factory.cs:line 64
   at OpenTK.NativeWindow..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device) in /home/jarl/Programming/opentk-3.0/src/OpenTK/NativeWindow.cs:line 109
   at OpenTK.NativeWindow..ctor(Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device) in /home/jarl/Programming/opentk-3.0/src/OpenTK/NativeWindow.cs:line 74
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext, Boolean isSingleThreaded) in /home/jarl/Programming/opentk-3.0/src/OpenTK/GameWindow.cs:line 186
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title) in /home/jarl/Programming/opentk-3.0/src/OpenTK/GameWindow.cs:line 119
   at OpenGL.Test.Test.Main(String[] args) in /home/kawaemon/Programming/OpenGL/OpenGL.Test/Program.cs:line 9

```

### Related information 

* Operating system: Arch Linux with Linux-5.0.7
* SDL or Native backend: xorg-server 1.20.4
* What version of OpenTK: The nuget's newest version. (3.0.1)
* What runtime: dotnet 2.2.105

**Comment by Perksey** [comment]
.NET Core is not supported at the moment. We only support .NET Framework and Mono.

**Comment by kawaemon** [comment]
Oh I'm sorry, I didn't know....
Thank you for support.
